version: '3'
services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - "/usercode/:/code"

  database:
    image: mongo:latest
    restart: always
    command: mongod --auth
    env_file:
      - .env
    volumes:
      - mongodbdata:/data/db
    depends_on:
      - web

  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - web

  redis:
    image: redis:alpine
    restart: always
    env_file: 
      - .env
    volumes:
      - .redis_data:/data

volumes:
  nginx_secrets:
  mongodbdata:
  redis_data: